### ISSUE TITLE
[FEATURE] Pull Request templates

### ISSUE THREAD

**Issue by Zakrok09** [TeamPraxidike/praxiConventions#26]

**Comment by Revirator** [comment]
Yeah, I meant PR templates in general. Imo if you just link a nicely-described issue (with acceptance criteria, etc.) there is nothing meaningful that a PR description can add.

**Comment by Revirator** [comment]
In GitHub, you can just link the issues to the PR 
![image](https://user-images.githubusercontent.com/74019630/233954054-a2598831-adfd-49eb-b094-14589fb1d327.png)
However, I prefer Bitbucket even more, where you just include the ticket nr inside [] in your commit message and you can just click on it:
![image](https://user-images.githubusercontent.com/74019630/233954732-944c3f9b-256c-4938-a59f-056886cee49f.png)
